on:
  push:
    branches:
      - main          # ← ブランチ指定
    tags:
      - 'v*.*.*'      # ← タグのパターン指定

jobs:
  prod_deploy:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && github.event.base_ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ref (branch or tag)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # - name: Check tagged branch
      #   run: |
      #     BRANCHS=$(git branch --contains ${{ github.ref_name }})
      #     set -- $BRANCHS
      #     for BRANCH in $BRANCHS ; do
      #       if [[ "$BRANCH" == "main" ]]; then
      #         exit 0
      #       fi
      #     done
      #     exit 1

      - id: get_branches
        name: Get branches containing commit
        run: |
          BRANCHES=$(git branch --contains ${{ github.sha }})
          echo "branches=$BRANCHES" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Generate HTML files with Redocly
        run: |
          mkdir -p out
          echo "<!DOCTYPE html>" > out/index.html
          echo "<html><head><title>API Docs for $REF_NAME</title></head><body>" >> out/index.html
          echo "<h1>Version: $BRANCHES</h1>" >> out/index.html
          echo "<h1>mainでpush</h1>" >> out/index.html
          echo "</body></html>" >> out/index.html
        env:
          REF_NAME: ${{ github.ref_name }}
          BRANCHES: ${{ steps.get_branches.outputs.branches }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_dir: ${{ github.ref_name }}
          publish_branch: gh-pages
